### PR TITLE
IE: Admin updates

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1849.

- [x] Update `region` placetype
- [x] Update `county` placetype
- [x] Update `localadmin` placetype
- [x] Supersede `localadmin` into `locality`
- [x] Update `locality` placetype
- [x] Flag records as coterminous
- [x] Create a dual hierarchy for Dublin
- [x] Clip the Dublin and Galway localities to their region parents
- [x] Update Cork geometry to smaller polygon, revert hier_label properties on locality points no longer inside locality polygon
- [x] Turn neighbourhood polygons in dublin into points, clean up
- [x] Mark Cork and Galway neighbourhoods as funky
- [x] Create new points for neighbourhoods in Cork and Galway
- [x] Clip all localities along the coast to their parent shape, store alt files
- [x] Review all new neighbourhood point records
- [x] PIP
- [x] Validate

### CODE REVIEW

**Comment by stepps00** [comment]
Commit Notes:

cf3bb22: Deprecates county subdivisions, currently at the `region` placetype (they'll become new counties)
a779e7a: Adds remaining, missing county records

2695506: Updates Cork and Galway `region` geometries

371999f: Creates a new `region` record for Dublin

3a38ede: Deprecates all `localadmin` records (these will later be superseded into `locality` records

c9d94a9: Updates existing `locality` records, updating geometries and properties. Centroids are untouched when within the source polygon. Also creates new `locality` records for settlements not currently in WOF.

**Comment by stepps00** [comment]
@nvkelso this PR is still a WIP, but ready to review on-screen.

**Comment by nvkelso** [comment]
Overall looking good. We discussed a few minor things:

- Clip Cork and Galway to their county shape
- Cork has a lot of leftover which should be removed, and the locality points restored (not made funky)
- Dublin has terrible neighbourhood polygons, make them points
- For Cork, Galway, and Dublin curate neighourhood points

**Comment by stepps00** [comment]
The remaining tasks in this PR have been completed, minus the hierarchy and PIP work.

I plan to let this PR settle, QA a bit more, run changes against the PIP tools, then merge (likely early next week).

**Comment by stepps00** [comment]
The most recent commit includes PIP work for this branch. There is a bit more work to manually curate a hierarchy for Dublin, ad validate this PR.. once complete, I'll QA a bitt more, then likely merge this PR.

**Pull request merged**
